### ISSUE TITLE
Spelling errors

### ISSUE THREAD

**Issue by Benjamin-51** [WildCodeSchool/purple-php-2109-project2-castle#40]
Here are some changes I'm suggesting.

- In terms of services
"**Its** authors". It's is a contraction of "it is".
"Acces to the site" should be "Access" and also probably "to the website"

- In the tutorial
First it should in my opinion, be called instructions, since a tutorial implies some kind of interactivity.
"You look up from your papers" sounds weird since "look up" is already a word, but maybe I'm wrong.
" In this game you will  have **to choose** the type of troop **you are sending** into battle"

Also the "How to win" section isn't named well since there is no way to win, only not to lose.

**Comment by sebastien-violante** [comment]
Hi Benjalin, for the fisrt suggest, "its" is "his" for an object and not for "it is"

**Comment by Benjamin-51** [comment]
Yes, that's why it's "its" and not "it's". Currently you wrote "**It's** authors".
It's true I should have mentioned that bolded sections are parts I already corrected without mentioning the original.

**Comment by sebastien-violante** [comment]
Hi Benjamin,  

Sorry, you're right for the first one ! 
In progress for the others... ;-)
